Controllers/AdminHomeController.cs
using Online_Learning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Online_Learning.Controllers
{
    public class AdminHomeController : Controller
    {
        OnlineLearningEntities1 userRepo  = new OnlineLearningEntities1();
        [HttpGet]
        public ActionResult Admin()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ProfileInfo(int id)
        {
            var result = from item in userRepo.Users
                         where item.UserID == id
                         select item;
          //    User profile = result.FirstOrDefault();
          //  User p = userRepo.Users.Where(x => x.UserID == id).FirstOrDefault();
          //  p.UserID = id;
          //  return View(p);
            return View(result.FirstOrDefault());
        }
        [HttpGet]
        public ActionResult Teachers()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Students()
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult Courses()
        {
            return View(userRepo.Courses.ToList());
        }
        [HttpGet]
        public ActionResult Blogs()
        {
            return View(userRepo.CourseMaterials.ToList());
        }
        [HttpGet]
        public ActionResult Messages()
        {
            return View();
        }

    }
}

Views/AdminHome/Admin.cshtml
@model Online_Learning.Models.User

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
</head>
<body>
    <h2>Admin Dashboard!!!</h2>
    <aside>
        <nav>
            <ul id="menu">
                <li>@Html.ActionLink("Profile", "Profile/", "AdminHome")</li>
                <li>@Html.ActionLink("Students List", "Students/", "AdminHome")</li>
                <li>@Html.ActionLink("Teachers List", "Teachers/", "AdminHome")</li>
                <li>@Html.ActionLink("All Courses", "Courses/", "AdminHome")</li>
                <li>@Html.ActionLink("Logout", "Logout/", "Login")</li>
            </ul>
        </nav>
    </aside>
</body>
</html>

Views/AdminHome/Blogs.cshtml
@model IEnumerable<Online_Learning.Models.CourseMaterial>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Blogs</title>
    <h2>Blogs</h2>
</head>
<body>
    <table class="table" border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cours.CourseName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileLink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cours.CourseName)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.MaterialID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.MaterialID })
                </td>
            </tr>
        }
        <ul id="menu">
            <li>@Html.ActionLink("Logout", "Logout/", "Login") |
            @Html.ActionLink("Back", "AdminDashboard/", "Login")</li>
            </ul>
    </table>
</body>
</html>

Views/AdminHome/Courses.cshtml
@model IEnumerable<Online_Learning.Models.Cours>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Courses</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table" border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseTeacher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseFee)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseTeacher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseFee)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.CourseID }) |
                @Html.ActionLink("Details", "Details", new { id=item.CourseID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.CourseID })
            </td>
        </tr>
    }
    <ul id="menu">
        <li>
            @Html.ActionLink("Logout", "Logout/", "Login") |
        @Html.ActionLink("Back", "AdminDashboard/", "Login")
    </li>
    </ul>
    </table>
</body>
</html>

Views/AdminHome/ProfileInfo.cshtml
@model Online_Learning.Models.User

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ProfileInfo</title>
</head>
<body>
    <div>
        <h4>User</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Username)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserType)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.UserID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    <ul id="menu">
        <li>
            @Html.ActionLink("Logout", "Logout/", "Login") |
        @Html.ActionLink("Back", "AdminDashboard/", "Login")
    </li>
</ul>
</body>
</html>